# Generated by Django 3.2 on 2021-04-24 11:59

from django.db import migrations, models
import korzinka.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(0, 'Все товары'), (1, 'Мука и продукты для выпечки'), (2, 'Крупы'), (3, 'Макаронные изделия'), (4, 'Растительные масла'), (5, 'Консервация'), (6, 'Соусы,приправы,маринады'), (7, 'Десертные продукты'), (8, 'Хлеб,батон,лепешки,лаваш'), (9, 'Сдобные изделия,выпечка'), (10, 'Хлебцы,сухари,сушки'), (11, 'Напитки'), (12, 'Рыба,морепродукты'), (13, 'Колбасные изделия'), (14, 'Молочные изделия'), (15, 'Сыры'), (16, 'Масло сливочное'), (17, 'Замороженные пельмены'), (18, 'Тесто,выпечка замороженная'), (19, 'Замороженные морепродукты')], default=0, verbose_name='Категория товаров')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(help_text='в сомах', null=True)),
                ('weight', models.PositiveSmallIntegerField(blank=True, help_text='в граммах', null=True)),
                ('volume', models.PositiveSmallIntegerField(blank=True, help_text='в миллилитрах', null=True)),
                ('image', models.ImageField(upload_to=korzinka.models.get_upload_path)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
